name: Build and Release

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build, Test and Release
    runs-on: ubuntu-latest

    env:
      PROJECT_NAME: "blockcore-extension"

    steps:
      - uses: actions/checkout@master
        name: Checkout

      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: "https://registry.npmjs.org"

      # Should we force a version or attempt to rely on pre-installed on build agent / production environment?
      # - name: Setup Node.js (${{ matrix.node_version }})
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: ${{ matrix.node_version }}

      - name: Variables
        run: |
          echo VERSION=$(npm run version --silent) >> $GITHUB_ENV
        shell: bash

      - name: Package Name
        run: |
          echo RELEASE_NAME=${{ env.PROJECT_NAME }}-${{ env.VERSION }}.zip >> $GITHUB_ENV
        shell: bash

      - name: Install and Build
        run: |
          npm ci
          npm run build
      # - name: Display structure of downloaded files
      #   run: ls -R

      # - name: Run Tests
      #   run: |
      #     npm run test

      - name: Package
        run: |
          zip -r ${{env.RELEASE_NAME}} dist/${{ env.PROJECT_NAME }}

      - uses: actions/upload-artifact@v1
        with:
          name: ${{env.PROJECT_NAME}}-preview-${{env.VERSION}}
          path: "${{env.RELEASE_NAME}}"

      - name: Release
        uses: sondreb/action-release@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: "${{env.RELEASE_NAME}}"
          draft: true
          prerelease: false
          name: "Blockcore Extension (Release ${{env.VERSION}})"
          tag: ${{env.VERSION}}
