name: Pull Request

on:
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    env:
      BLOCKCORE: "blockcore"
      COINVAULT: "coinvault"
      FREECITY: "freecity"

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: true

      - uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"

      - name: Variables
        run: |
          echo VERSION=$(npm run version --silent) >> $GITHUB_ENV
        shell: bash

      - name: Package Name
        run: |
          echo RELEASE_NAME_BLOCKCORE=${{ env.BLOCKCORE }}-${{ env.VERSION }}.zip >> $GITHUB_ENV
          echo RELEASE_NAME_COINVAULT=${{ env.COINVAULT }}-${{ env.VERSION }}.zip >> $GITHUB_ENV
          echo RELEASE_NAME_FREECITY=${{ env.FREECITY }}-${{ env.VERSION }}.zip >> $GITHUB_ENV
        shell: bash

      - name: Setup
        run: npm ci

      - name: Test
        run: npm test -- --no-watch --no-progress --browsers=ChromeHeadless

      - name: Build
        run: npm run all
